// caveman:native-opencode — GENERATED by `caveman enable opencode`.
// Contract: @opencode-ai/plugin 1.17.8 Hooks (installed local type source).
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";

const command = "/home/x3/.npm-global/bin/caveman";
const prefix = [];
const contexts = new Map();
const pending = new Map();

function call(event, payload = {}) {
  try {
    const raw = execFileSync(command, [...prefix, "native-hook", "opencode", event], {
      input: JSON.stringify({ event_name: event, ...payload }),
      encoding: "utf8",
      timeout: 2000,
      maxBuffer: 2 * 1024 * 1024,
    });
    if (!raw.trim()) return undefined;
    const value = JSON.parse(raw);
    return value && typeof value === "object" ? value : undefined;
  } catch { return undefined; }
}

function digest(value) {
  try {
    const raw = JSON.stringify(value);
    return { bytes: Buffer.byteLength(raw), sha256: "sha256:" + createHash("sha256").update(raw).digest("hex") };
  } catch { return undefined; }
}

function taskType(value) {
  let text;
  try { text = JSON.stringify(value).toLowerCase(); } catch { return "general"; }
  const has = (...terms) => terms.some((term) => text.includes(term));
  if (has("migration", "migrate", "schema change", "backfill", "rollback")) return "migration";
  if (has("bug", "fix", "broken", "regression", "crash", "error", "incorrect")) return "bugfix";
  if (has("investigate", "diagnose", "root cause", "why does", "trace")) return "investigation";
  if (has("refactor", "restructure", "reorganize", "cleanup")) return "refactor";
  if (has("review", "audit", "critique", "assess")) return "review";
  if (has("verify", "verification", "prove", "validate", "check that")) return "verification";
  if (has("build", "implement", "add", "create", "ship", "feature")) return "feature";
  return "general";
}

function taskTerms(value) {
  let text;
  try { text = JSON.stringify(value); } catch { return []; }
  const stop = new Set(["about", "after", "agent", "before", "build", "change", "code", "create", "from", "have", "help", "implement", "into", "make", "please", "project", "repository", "should", "spec", "task", "that", "then", "there", "these", "they", "this", "through", "user", "want", "what", "when", "where", "which", "with", "would", "your"]);
  const out = [];
  const seen = new Set();
  for (const raw of text.match(/[A-Za-z][A-Za-z0-9_./-]{2,63}/g) ?? []) {
    const term = raw.toLowerCase().replace(/^[-./]+|[-./]+$/g, "");
    if (!term || term.includes("..") || stop.has(term) || seen.has(term) || /^(?:sk|pk|rk|ghp|github_pat|xox[baprs]|akia)[-_]/i.test(term) || /^[a-z0-9_-]{40,}$/i.test(term)) continue;
    seen.add(term);
    out.push(term);
    if (out.length === 12) break;
  }
  return out;
}

function taskContinuation(value) {
  const visit = (item) => {
    if (typeof item === "string") return item;
    if (Array.isArray(item)) return item.map(visit).filter(Boolean).join(" ");
    if (!item || typeof item !== "object") return "";
    return visit(item.text ?? item.content ?? item.message ?? "");
  };
  const prompt = visit(value).trim().toLowerCase();
  if (!prompt || prompt.length > 160 || prompt.split(/s+/).length > 14) return false;
  return /^(?:pleases+)?(?:continue|go ahead|keep going|proceed|do (?:it|that)|fix (?:it|that)|retry|try again|explain (?:it|that)|what do you mean|yes|yep|yeah|why??|how??)[.!?s]*$/.test(prompt);
}

function sessionContext(sessionID) {
  if (!sessionID) return undefined;
  if (!contexts.has(sessionID)) {
    const out = call("SessionStart", { session_id: sessionID, surface: "cli" });
    const context = out?.hookSpecificOutput?.additionalContext;
    if (typeof context === "string" && context) contexts.set(sessionID, context);
  }
  return contexts.get(sessionID);
}

export const CavemanNative = async () => ({
  event: async ({ event }) => {
    const type = event?.type;
    const props = event?.properties ?? {};
    const sessionID = props.sessionID ?? props.info?.id;
    if (type === "session.created") sessionContext(sessionID);
    if (type === "session.idle") call("Stop", { session_id: sessionID });
    if (type === "session.compacted") {
      const out = call("PostCompact", { session_id: sessionID });
      const context = out?.hookSpecificOutput?.additionalContext;
      if (typeof context === "string" && context) contexts.set(sessionID, context);
    }
    if (type === "session.deleted") {
      call("SessionEnd", { session_id: sessionID });
      contexts.delete(sessionID);
      pending.delete(sessionID);
    }
  },
  "chat.message": async (input, output) => {
    const decision = call("UserPromptSubmit", {
      session_id: input.sessionID,
      model: input.model?.modelID,
      provider: input.model?.providerID,
      prompt: digest(output?.parts),
      task_type: taskType(output?.parts),
      task_terms: taskTerms(output?.parts),
      task_continuation: taskContinuation(output?.parts),
    });
    const dynamic = decision?.hookSpecificOutput?.additionalContext;
    if (typeof dynamic === "string" && dynamic) pending.set(input.sessionID, dynamic);
  },
  "experimental.chat.system.transform": async (input, output) => {
    const stable = sessionContext(input.sessionID);
    if (stable) output.system.push(stable);
    const hint = pending.get(input.sessionID);
    if (hint) {
      output.system.push(hint);
      pending.delete(input.sessionID);
    }
  },
  "tool.execute.before": async (input, output) => {
    const decision = call("PreToolUse", {
      session_id: input.sessionID,
      tool_name: input.tool,
      tool_input: output.args,
    });
    if (typeof decision?.hookSpecificOutput?.additionalContext === "string") {
      pending.set(input.sessionID, decision.hookSpecificOutput.additionalContext);
    }
    if (input.tool !== "bash" || typeof output?.args?.command !== "string") return;
    try {
      const raw = execFileSync(command, [...prefix, "shrink-hook"], {
        input: JSON.stringify({ tool_name: "Bash", tool_input: { command: output.args.command } }),
        encoding: "utf8",
        timeout: 750,
      });
      const rewritten = JSON.parse(raw)?.hookSpecificOutput?.updatedInput?.command;
      if (typeof rewritten === "string" && rewritten) output.args.command = rewritten;
    } catch {}
  },
  "tool.execute.after": async (input, output) => {
    const decision = call("PostToolUse", {
      session_id: input.sessionID,
      tool_name: input.tool,
      tool_input: input.args,
      tool_output: output.output,
    });
    if (typeof decision?.hookSpecificOutput?.updatedToolOutput === "string") {
      output.output = decision.hookSpecificOutput.updatedToolOutput;
    } else if (typeof decision?.output_replacement === "string") {
      output.output = decision.output_replacement;
    }
  },
  "experimental.session.compacting": async (input, output) => {
    call("PreCompact", { session_id: input.sessionID });
    const stable = sessionContext(input.sessionID);
    if (stable) output.context.push(stable);
  },
  dispose: async () => {
    for (const sessionID of contexts.keys()) call("SessionEnd", { session_id: sessionID });
    contexts.clear();
    pending.clear();
  },
});
